# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'DigiCARES'
theme: tessellate
copyright: '&copy; DigiCARES 2025'

#     ______      ____          __  _                 
#    / ____/___  / / /__  _____/ /_(_)___  ____  _____
#   / /   / __ \/ / / _ \/ ___/ __/ / __ \/ __ \/ ___/
#  / /___/ /_/ / / /  __/ /__/ /_/ / /_/ / / / (__  ) 
#  \____/\____/_/_/\___/\___/\__/_/\____/_/ /_/____/  
#                                                     
collections:
  news:
    output: false
    sort_by: date
  team:
    output: false
    sort_by: sort_order

# Social Media
socials:
  - name: Website
    link: https://digicares.net
    icon_class: 'solid fas fa-globe'
  - name: GitHub
    link: https://github.com



